services:
  web:
    build: .
    ports:
      - "8031:80"
    volumes:
      - ./www:/var/www/html
      - ./src/cgi:/usr/lib/cgi-bin
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped
