services:
  server:
    build: .
    ports:
      - "8031:80"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TZ=Asia/Tokyo
    command: ruby -run -e httpd . -p 80 -b 0.0.0.0
