---
services:
  web:
    build:
      context: .
      args:
        BASE_URL: "http://localhost:8080/"
        CGI_BASE_URL: "http://localhost:8080/cgi-bin/"
    ports:
      - "8080:80"
    volumes:
      - .:/app
    restart: unless-stopped
